services:
  hray_server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - GROQ_API_KEY
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true            # Enable OTLP receiver
    ports:
      # OTLP gRPC and HTTP ports
      - "4317:4317"   # OTLP gRPC (primary protocol for OTLPSpanExporter)
      - "4318:4318"   # OTLP HTTP

      # Standard Jaeger ports (can keep for compatibility)
      - "16686:16686" # UI
      - "14250:14250" # Model.proto
      - "14268:14268" # Jaeger HTTP
      - "14269:14269" # Admin port

      # Optional: Keep these only if you need backward compatibility
      # - "5775:5775/udp"    # Agent - zipkin.thrift
      # - "6831:6831/udp"    # Agent - jaeger.thrift compact
      # - "6832:6832/udp"    # Agent - jaeger.thrift binary
      # - "5778:5778"        # Agent configs
      # - "9411:9411"        # Zipkin compatible endpoint
