services:
  hray_server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - GROQ_API_KEY
      - GROQ_MODEL
      - JAEGER_HOST=jaeger
      - PHOENIX_HOST=phoenix
    depends_on:
      - phoenix
    networks:
      - my_bridge_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - my_bridge_network

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
    environment:
      - PHOENIX_AUTH_ENABLED=false
      - PHOENIX_OTLP_ENDPOINT=jaeger:4317
      - PHOENIX_TRACE_ENABLED=true
    depends_on:
      - jaeger
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge
