services:
  hray_server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - GROQ_API_KEY
    depends_on:
      - phoenix

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      # OTLP gRPC and HTTP ports
      # - "4317:4317"   # OTLP gRPC (primary protocol for OTLPSpanExporter)
      - "4318:4318"   # OTLP HTTP

      - "16686:16686" # UI
      - "14250:14250" # Model.proto
      - "14268:14268" # Jaeger HTTP
      - "14269:14269" # Admin port
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "4317:4317"
      - "6006:6006"    # Phoenix UI
    environment:
      - PHOENIX_AUTH_ENABLED=false  # Disable auth for local development
      - PHOENIX_OTLP_ENDPOINT=jaeger:4317  # Connect to Jaeger OTLP endpoint
      - PHOENIX_TRACE_ENABLED=true         # Enable tracing
    depends_on:
      - jaeger
