services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"  # Accept jaeger.thrift in compact Thrift protocol
      - "6832:6832/udp"  # Accept jaeger.thrift in binary Thrift protocol
      - "5778:5778"      # Serve configs
      - "16686:16686"    # Serve frontend
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
      - "14250:14250"    # Accept model.proto
      - "14268:14268"    # Accept jaeger.thrift directly from clients
      - "14269:14269"    # Admin port
    environment:
      #- COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
